//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoHoteles.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        public int IdReserva { get; set; }
        public Nullable<int> IdHotel { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public string IdHabitacion { get; set; }
        public Nullable<int> IdTemporada { get; set; }
        public Nullable<System.DateTime> FechaReservacion { get; set; }
        public Nullable<System.DateTime> FechaActual { get; set; }
    }
}
